-   id: pylint
    name: pylint
    description: ''
    entry: pylint
    language: python
    'types': [python]
    args: ["--score=n"]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '0'
